name: WorldHunts
version: 0.1
main: tk.mjsv.WorldHunter
api-version: 1.17
authors: [ minjae9010, Luni5 ]
description: 땅따먹기 플러그인
depend: [LuckPerms]
commands:
  팀:
    description: 팀 명령어
  타이머:
    description: 타이머
  공지:
    description: 공지 명령어
  남은시간:
    description: 타이머 남은시간
  땅:
    description: 땅 명령어
  지명수배:
    description: 지명수배 명령어
  초대:
    description: 화이트리스트
  전쟁:
    description: 전쟁명령어